### PR TITLE
Pass through SWIFT_DRIVER_SWIFT_FRONTEND_EXEC if set

### LINKED ISSUE #855: SWIFT_DRIVER_SWIFT_FRONTEND_EXEC Ignored by swift-build system
When building with the Swift Build System (--build-system swiftbuild), the environment variable `SWIFT_DRIVER_SWIFT_FRONTEND_EXEC` is ignored. As a result, swift build always invokes the system toolchain’s swift-frontend instead of the custom frontend specified by the environment variable.

Steps to Reproduce

Create a simple Swift package:
```bash
mkdir -p /tmp/swiftbuild-env-test && cd /tmp/swiftbuild-env-test
swift package init --type executable --name EnvTest
```

Test 1: Native Build System (works)

```
cd /tmp/swiftbuild-env-test
rm -rf .build
# Use a custom swift-frontend and pass -Xswiftc -v to confirm
env SWIFT_DRIVER_SWIFT_FRONTEND_EXEC=/Users/ryan_mansfield/swift/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend \
  swift build -Xswiftc -v 2>&1 | grep "swift-frontend.*-frontend.*-c" | head -1

```

Result:

Shows the custom frontend being used:
`/Users/ryan_mansfield/swift/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend -frontend -c -primary-file /private/tmp/swiftbuild-env-test/Sources/EnvTest/main.swift ...
`

Test 2: Swift Build System (doesn't work)

```
cd /tmp/swiftbuild-env-test
rm -rf .build

# Use the same custom frontend with the Swift Build system
env SWIFT_DRIVER_SWIFT_FRONTEND_EXEC=/Users/ryan_mansfield/swift/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend \
  swift build --build-system swiftbuild -Xswiftc -v 2>&1 | grep "swift-frontend.*-frontend.*-c" | head -1

```
Result:

The system toolchain frontend is used instead:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /private/tmp/swiftbuild-env-test/Sources/EnvTest/main.swift ...`

Expected Behavior

swift build should respect the `SWIFT_DRIVER_SWIFT_FRONTEND_EXEC` environment variable and use the specified custom swift-frontend for all compilation tasks, regardless of the build system used.

Actual Behavior
When using the Swift Build System (--build-system swiftbuild), the `SWIFT_DRIVER_SWIFT_FRONTEND_EXEC` environment variable is ignored, and the system toolchain’s swift-frontend is always used.

### PR DESCRIPTION
**Pull request by rjmansfield**
Fixes #855

### CODE REVIEW

**Comment by rjmansfield** [comment]
@swift-ci please test

File: Sources/SWBCore/SpecImplementations/Tools/SwiftCompiler.swift [hunk 1]
```diff
@@ -757,6 +757,18 @@ public final class SwiftCompilerSpec : CompilerSpec, SpecIdentifierType, SwiftDi
         }
     }
 
+    override public func environmentFromSpec(_ cbc: CommandBuildContext, _ delegate: any DiagnosticProducingDelegate, lookup: ((MacroDeclaration) -> MacroExpression?)? = nil) -> [(String, String)] {
+        var env: [(String, String)] = super.environmentFromSpec(cbc, delegate, lookup: lookup)
+
+        // Pass through SWIFT_DRIVER_SWIFT_FRONTEND_EXEC if set in the process environment.
+        // This is consumed by the driver to select which swift-frontend binary to use.
+        if let frontendExec = ProcessInfo.processInfo.environment["SWIFT_DRIVER_SWIFT_FRONTEND_EXEC"] {
```
Comment (jakepetroules) [inline Sources/SWBCore/SpecImplementations/Tools/SwiftCompiler.swift]: We should not use globals like `ProcessInfo.processInfo.environment`; the process environment is captured into the `WorkspaceContext` as `buildSystemEnvironment`. That said, we populate the builtin macros from the `WorkspaceContext.buildSystemEnvironment` already, so I think this value should be present in the `cbc.scope`.

**Review by jakepetroules — APPROVED** [review]

**Comment by rjmansfield** [comment]
@swift-ci please test
