### PR TITLE
Resolves #263 - Add all valid architectures for windows cross compilation

### LINKED ISSUE #263: Windows: Cross architecture compilation not possible
Cross compilation does not work on Windows when it should be possible.

When on an arm64 host system, and setting ARCHS = "x86_64" a warning will be emitted.

`→ found unexpected warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (aarch64). (in target 'CommandLineTool' from project 'TestProject')`

VALID_ARCHS is only "aarch64"

### PR DESCRIPTION
**Pull request by kcieplak**
* The fallback SDK registration was only adding the host architecture as a valid architecture.  Add all valid architectures for Windows cross compilation.

### CODE REVIEW

**Comment by kcieplak** [comment]
@swift-ci test

File: Sources/SWBCore/SDKRegistry.swift [hunk 1]
```diff
@@ -662,6 +662,12 @@ public final class SDKRegistry: SDKRegistryLookup, CustomStringConvertible, Send
             tripleEnvironment = ""
         }
 
+        let archs: PropertyListItem = switch operatingSystem {
+            case .windows:
+                .plArray([.plString("x86_64"), .plString("aarch64")])
```
Comment (jakepetroules) [inline Sources/SWBCore/SDKRegistry.swift:667]: `i686` is also supported by the Swift toolchain; we should add that too.

I'd also add `armv7` (32-bit) (CC @compnerd for the specific spelling) since it's technically still supported by the Microsoft toolchains and you could build a C package for Windows IoT if you really wanted to. The Swift toolchain doesn't currently include it but I just checked with @compnerd and he said he'd be open to adding it.

**Review by jakepetroules — CHANGES_REQUESTED** [review]

**Comment by jakepetroules** [comment]
I think you'll also want to change Windows.xcspec to default `ARCHS_STANDARD` to `$(HOST_ARCH)` instead of `$(VALID_ARCHS)` since building for multiple archs is not really going to work correctly on non-Apple platforms at this time.

File: Sources/SWBCore/SDKRegistry.swift (hunk 1 above)
Comment (kcieplak) [reply Sources/SWBCore/SDKRegistry.swift:667]: clang also supports a few others...

`Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64`

**Comment by kcieplak** [comment]
> I think you'll also want to change Windows.xcspec to default `ARCHS_STANDARD` to `$(HOST_ARCH)` instead of `$(VALID_ARCHS)` since building for multiple archs is not really going to work correctly on non-Apple platforms at this time.

I did notice that if you set ARCHS = "x86_64 aarch64" only one was ever built for.  That explains that.

**Comment by kcieplak** [comment]
@swift-ci test
